Resources:

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/create-task.handler
      Runtime: nodejs16.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks
            Method: post

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/get-task.handler
      Runtime: nodejs16.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: get

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/update-task.handler
      Runtime: nodejs16.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/delete-task.handler
      Runtime: nodejs16.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: delete
